front:
  build: .
  ports:
    - "80:80"
    - "443:443"
    - "9000:9000"
  links:
    - mysql:mysql
  volumes:
    - ./www:/var/www
    - ./sites:/etc/nginx/conf.d
    - ./logs:/var/log/supervisor

mysql:
  image: mysql
  volumes:
    - ./mysql:/var/lib/mysql
  ports:
    - "3307:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password
